#pragma once

#define FRANNEL_DISABLE_DYNAMIC_LED_MODE

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define DEFAULT_LED0_MODE FR_LED_NUMLOCK
#define DEFAULT_LED1_MODE FR_LED_SOLENOID
#define DEFAULT_HAPTIC_LED_NO 1
