#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define DEFAULT_LED0_MODE FR_LEDMODE_NUMLOCK
#define DEFAULT_LED1_MODE FR_LEDMODE_SOLENOID
#define DEFAULT_HAPTIC_LED_NO 1

// #define FRANNEL_DISABLE_DYNAMIC_LED_MODE
