#pragma once

/* Cirque trackpad */
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7
#undef CIRQUE_PINNACLE_DIAMETER_MM
#define CIRQUE_PINNACLE_DIAMETER_MM 35
// #define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_ABSOLUTE_MODE
