#pragma once

#define MK_COMBINED

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 6
#define MOUSEKEY_TIME_TO_MAX 64

#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_DELTA 1
#define MOUSEKEY_WHEEL_MAX_SPEED 2
#define MOUSEKEY_WHEEL_INTERVAL 200

#define TAPPING_TERM 200
#define TAP_HOLD_CAPS_DELAY 20

#define COMBO_TERM 50
